use_frameworks!

platform :ios, '8.0'

target 'KYPhotoBrowser_Example' do
  pod 'KYPhotoBrowser', :path => '../'

  target 'KYPhotoBrowser_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
